find_program(CMAKE_C_COMPILER NAMES $ENV{CC} gcc-8 PATHS ENV PATH NO_DEFAULT_PATH)
find_program(CMAKE_CXX_COMPILER NAMES $ENV{CXX} g++-8 PATHS ENV PATH NO_DEFAULT_PATH)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)